version: '3.8'

services:
  neo4j:
    image: neo4j:5.12.0
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/password  # Change for production
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
    volumes:
      - ./data/neo4j:/data
      - ./data/neo4j/plugins:/plugins
      - ./data/neo4j/import:/import

  knowledge_storage_mcp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - neo4j
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password  # Change for production
      - LOG_LEVEL=INFO
    volumes:
      - ./:/app
